config/routes.php
<?php
use Cake\Routing\Router;

Router::plugin('IconicSeo', function(\Cake\Routing\RouteBuilder $route) {
	$route->connect('/:controller/');
	$route->connect('/:controller/:action');
	$route->connect('/:controller/:action/*');
});

src/Model/Entity/SeoMetaTag.php
<?php
/**
 * Created by PhpStorm.
 * User: tanbt
 * Date: 05/06/2015
 * Time: 09:25
 */

namespace IconicSeo\Model\Entity;

use Cake\ORM\Entity;
use IconicSeo\Model\Behavior\Traits\SeoEscapeTrait;

class SeoMetaTag extends Entity {

    use SeoEscapeTrait;

    /**
     * @return string
     * Example: name="description"
     */
    protected function _getAttribute1(){
        $return_str = '';
        if($this->checkAttribute1Title($this->_properties['attribute1_title'])){
            $return_str = "{$this->_properties['attribute1_title']}=";

            if($this->checkAttribute1Content($this->_properties['attribute1_content'])){
                $return_str .= "\"{$this->_properties['attribute1_content']}\"";
            } else {
                $return_str .= "\"\"";
            }
        }
        return $return_str;
    }

    /**
     * @return string
     * Example: content="Some of your content"
     */
    protected function _getAttribute2(){
        $return_str = '';

        if(!empty($this->_properties['attribute2_title'])){
            $return_str = "{$this->_properties['attribute2_title']}=";

            if(!empty($this->_properties['attribute2_content'])){
                $return_str .= "\"{$this->_properties['attribute2_content']}\"";
            } else {
                $return_str .= "\"\"";
            }
        }
        return $return_str;
    }

}

src/Controller/UrisController.php
<?php
namespace IconicSeo\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Seo\Model\TextTag;
use Seo\SeoDefault;

class UrisController extends AppController
{

    //http://iconic-intl.local/iconic_seo/uris
    public function index()
    {
        $filter = $this->request->query('filter') ? $this->request->query('filter') : 'all';
        $orderBy = $this->request->query('order') ? $this->request->query('order') : '';

        $this->set('page_title', 'URIs SEO Management');

        $seo_uris = TableRegistry::get('IconicSeo.SeoUris');
        $query = $seo_uris->find('all')
            ->contain(['SeoTitles', 'SeoMetaTags', 'SeoCanonicals', 'SeoRedirects', 'SeoTopMessages', 'SeoFooterKeywords']);

        switch ($filter) {
            case 'jobs_dir':
                $query->where(['SeoUris.type' => 4]);
                break;
            case 'static_pages':
                $query->where(['SeoUris.type' => 2]);
                break;
            case 'other':
                $query->where(['SeoUris.type NOT IN' => [2, 4]]);
                break;
            default:
                break;
        }

        switch ($orderBy) {
            case 'created':
                $query->order(['SeoUris.created' => 'DESC']);
                break;
            case 'modified':
                $query->order(['SeoUris.modified' => 'DESC']);
                break;
            default:
                break;
        }

        if ($this->request->query('kw')) {
            $kw = $this->request->query('kw');
            $query->where(['SeoUris.uri LIKE ' => "%{$kw}%"]);
            $this->set('kw', $kw);
        }

        $this->paginate = [
            'limit' => 20
        ];
        $this->set('all_uris', $this->paginate($query));
    }

    public function edit($id)
    {
        $this->set('page_title', 'URIs SEO Management > URI');

        $seo_uris = TableRegistry::get('IconicSeo.SeoUris');
        $uri = $seo_uris->get($id, [
            'contain' => ['SeoTitles', 'SeoMetaTags', 'SeoCanonicals', 'SeoRedirects', 'SeoTopMessages', 'SeoFooterKeywords']
        ]);

        if ($this->request->is(['post', 'put'])) {

            $seo_uris->patchEntity($uri, $this->request->data, [
                'associated' => ['SeoTitles', 'SeoCanonicals', 'SeoRedirects', 'SeoTopMessages', 'SeoFooterKeyWords']
            ]);

            if ($uri->dirty('title')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['title']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('canonical')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['canonical']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('en_top_message')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['en_top_message']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('ja_top_message')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['ja_top_message']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('vi_top_message')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['vi_top_message']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('en_keywords')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['en_keywords']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('ja_keyword')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['ja_keywords']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('vi_keyword')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['vi_keywords']['modified'] = date('Y-m-d H:i:s');
            }
            if ($uri->dirty('redirect')) {
                $this->request->data['modified'] = date('Y-m-d H:i:s');
                $this->request->data['redirect']['modified'] = date('Y-m-d H:i:s');
            }

            $seo_uris->patchEntity($uri, $this->request->data, [
                'associated' => ['SeoTitles', 'SeoCanonicals', 'SeoRedirects', 'SeoFooterKeywords', 'SeoTopMessages']
            ]);
            if ($seo_uris->save($uri)) {
                $this->Flash->success(__('URI has been updated.'));
            }
        }

        $this->set('uri', $uri);
    }

    /*
    public function changeStatus(){
        $uri_id = $this->request->query('id');
        $page   = $this->request->query('page');

        $seo_uris = TableRegistry::get('IconicSeo.SeoUris');
        $uri = $seo_uris->get($uri_id);
        $uri->is_approved = ($uri->is_approved + 1) % 2;
        $uri->modified = date('Y-m-d H:i:s');
        if($seo_uris->save($uri)){
            $this->Flash->success("Uri '{$uri_id}' has been updated.");
        }

        return $this->redirect(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index',
            '#' => "uri_{$uri_id}",
            '?' => ['page' => $page],
        ]);
    }
    */

    public function deleteUri()
    {
        $uri_id = $this->request->query('id');
        $page = $this->request->query('page');

        $seo_uris = TableRegistry::get('IconicSeo.SeoUris');
        $uri = $seo_uris->get($uri_id);
        if ($seo_uris->delete($uri)) {
            TableRegistry::get('IconicSeo.SeoTitles')->deleteAll(['seo_uri_id' => $uri_id]);
            TableRegistry::get('IconicSeo.SeoCanonicals')->deleteAll(['seo_uri_id' => $uri_id]);
            TableRegistry::get('IconicSeo.SeoMetaTags')->deleteAll(['seo_uri_id' => $uri_id]);
            TableRegistry::get('IconicSeo.SeoRedirects')->deleteAll(['seo_uri_id' => $uri_id]);

            $this->Flash->success("Uri '{$uri_id}' has been deleted.");
        }

        return $this->redirect(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index',
            '#' => "uri_{$uri_id}",
            '?' => ['page' => $page],
        ]);
    }

    /**
     * Don't convert redirect link because it can cause unlimited loop
     * <meta http-equiv="refresh" content="0; url=http://example.com/" />
     */
    public function convert()
    {
        echo "Converting...<br/>";

        $seo_uris = TableRegistry::get('IconicSeo.SeoUris');
        $all_uris = $seo_uris->find('all')
            ->contain(['SeoTitles', 'SeoMetaTags', 'SeoCanonicals', 'SeoRedirects', 'SeoTopMessages', 'SeoFooterKeywords'])
            ->order(['uri' => 'ASC'])
            ->toArray();

        foreach ($all_uris as $uri_obj) {
            $full_uri = rtrim(PROTOCOL . "://" . $_SERVER["HTTP_HOST"] . $uri_obj->uri, '/');
            $seo_new_obj = new SeoDefault($full_uri);
            $seo_new_obj
                /*->addMetaTag(
                    [
                        'http-equiv'      => 'refresh',
                        'content'         => "0; url={$uri_obj->redirect}"
                    ]
                )*/
                ->addHtmlTag('title', $uri_obj->title->title)
                ->addLinkTag(
                    ['rel'=>'canonical', 'href' => $uri_obj->canonical->canonical]
                )

                ->addTextTag(TextTag::FOOTER_KEYWORDS, $uri_obj->footer_keyword->ja_keywords ?? '', 'JA')
                ->addTextTag(TextTag::FOOTER_KEYWORDS, $uri_obj->footer_keyword->en_keywords ?? '', 'EN')
                ->addTextTag(TextTag::FOOTER_KEYWORDS, $uri_obj->footer_keyword->vi_keywords ?? '', 'VI')

                ->addTextTag(TextTag::TOP_MESSAGE, $uri_obj->top_message->ja_top_message ?? '', 'JA')
                ->addTextTag(TextTag::TOP_MESSAGE, $uri_obj->top_message->en_top_message ?? '', 'EN')
                ->addTextTag(TextTag::TOP_MESSAGE, $uri_obj->top_message->vi_top_message ?? '', 'VI');

            foreach ($uri_obj->meta_tags as $meta_tag) {
                $seo_new_obj->addMetaTag(
                    [
                        $meta_tag->attribute1_title => $meta_tag->attribute1_content,
                        $meta_tag->attribute2_title => $meta_tag->attribute2_content
                    ]
                );
            }
            $seo_new_obj->save();
            echo "Done: {$full_uri}<br/>";
        }
        echo 'FINISH!!!';
        return $this->redirect(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index']);
        $this->autoRender = false;
    }
}

src/Template/Uris/edit.ctp
<?php
echo $this->Html->css(['/vendor/bootstrap/dist/css/bootstrap.min.css', 'IconicSeo.seo_plugin.css']);
?>
<br/>
<div class="row container" id="edit-uri">
    <div class="row">
        <div class="col-xs-12">
            <?= $this->Flash->render()?>
        </div>
    </div>

    <br/>

    <?=$this->Form->create($uri);?>
    <div class="row">
        <div class="col-xs-12 col-sm-5">
            <?=$this->Form->label('title.title', 'Page Title')?>
            <?=$this->Form->input('title.title', [
                'default'   => !empty($uri->title) ? $uri->title->title : '',
                'label'     => false,
                  'required'  => TRUE,
                'class'     => 'form-control',
            ]);?>
        </div>

        <div class="col-xs-10 col-sm-5">
            <?=$this->Form->label('canonical.canonical', 'Canonical Link')?>
            <?=$this->Form->input('canonical.canonical', [
                'default'   => !empty($uri->canonical) ? $uri->canonical->canonical: '',
                'label'     => false,
                'required'  => TRUE,
                'class'     => 'form-control',
            ]);?>
        </div>
        <div class="col-xs-2 col-sm-2">
            <?=$this->Form->label('canonical.is_active', 'Status')?>
            <?php
            $options = [1 => __('Active'), 0 => __('Disabled')];
            $default_status = 1;
            if(isset($uri->canonical->is_active) && $uri->canonical->is_active == 0){
                $default_status = 0;
            }
            echo $this->Form->select('canonical.is_active', $options, [
                'default' => $default_status,
                'class'     => 'form-control'
            ]);?>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-xs-10 col-sm-4">
            <?=$this->Form->label('top_message.top_message', 'Top message(JA)')?>
            <?=$this->Form->input('top_message.ja_top_message', [
                //'default'   => !empty($uri->top_message) ? $uri->top_message->ja_top_message: '',
                'label'     => false,
                'class'     => 'form-control',
            ]);?>
        </div>
        <div class="col-xs-10 col-sm-4">
            <?=$this->Form->label('top_message.top_message', 'Top message(EN)')?>
            <?=$this->Form->input('top_message.en_top_message', [
                //'default'   => !empty($uri->top_message) ? $uri->top_message->en_top_message: '',
                'label'     => false,
                'class'     => 'form-control',
            ]);?>
        </div>
        <div class="col-xs-10 col-sm-4">
            <?=$this->Form->label('top_message.top_message', 'Top message(VI)')?>
            <?=$this->Form->input('top_message.vi_top_message', [
                //'default'   => !empty($uri->top_message) ? $uri->top_message->vi_top_message: '',
                'label'     => false,
                'class'     => 'form-control',
            ]);?>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-xs-12 col-sm-4">
            <?=$this->Form->label('footer_keyword.ja_keywords', 'Footer keywords(JA)')?>
            <?=$this->Form->input('footer_keyword.ja_keywords', [
                'label'     => false,
                'class'     => 'form-control',
                'rows'       =>'1'
            ]);?>
        </div>
        <div class="col-xs-12 col-sm-4">
            <?=$this->Form->label('footer_keyword.en_keywords', 'Footer keywords(EN)')?>
            <?=$this->Form->input('footer_keyword.en_keywords', [
                'label'     => false,
                'class'     => 'form-control',
                'rows'       =>'1'
            ]);?>
        </div>
        <div class="col-xs-12 col-sm-4">
            <?=$this->Form->label('footer_keyword.vi_keywords', 'Footer keywords(VI)')?>
            <?=$this->Form->input('footer_keyword.vi_keywords', [
                'label'     => false,
                'class'     => 'form-control',
                'rows'       =>'1'
            ]);?>
        </div>
    </div>
    <br/>
    <div class="row">

    </div>
    <br/>
    <div class="row">

    </div>
    <br/>

    <div class="row">
        <?php if(!empty($uri->redirect)){ ?>
        <div class="col-xs-9">
            <?=$this->Form->label('redirect.redirect', 'Redirect Link')?>
            <?=$this->Html->link(
                '<span class="label label-danger">Delete</span>',
                ['plugin' => 'IconicSeo', 'controller' => 'Redirects', 'action' => 'delete', $uri->redirect->id],
                ['confirm' => 'Are you sure you wish to cancel?', 'escape' => false]
            )?>
            <?=$this->Form->input('redirect.redirect', [
                'default'   => $uri->redirect->redirect,
                'label'     => false,
                'required'  => TRUE,
                'class'     => 'form-control',
            ]);?>
        </div>
        <div class="col-xs-1">
            <?=$this->Form->label('redirect.type', 'Type')?>
            <?php
            $options = [301 => '301', 302 => '302'];
            $default_status = 302;
            if(isset($uri->redirect)){
                $default_status = $uri->redirect->type;
            }
            echo $this->Form->select('redirect.type', $options, [
                'default' => $default_status,
                'class'     => 'form-control'
            ]);?>
        </div>

        <div class="col-xs-2">
            <?=$this->Form->label('redirect.is_active', 'Status')?>
            <?php
            $options = [0 => __('Disabled'), 1 => __('Active')];
            $default_status = 0;
            if(isset($request->is_active)){
                $default_status = $request->is_active;
            }
            echo $this->Form->select('redirect.is_active', $options, [
                'default' => $default_status,
                'class'     => 'form-control'
            ]);?>
        </div>
        <?php } else { ?>
            <div class="col-xs-12" style="font-size: 16px">
                <?=$this->Html->link(
                    '<span class="label label-default">Add redirection</span>',
                    ['plugin' => 'IconicSeo', 'controller' => 'Redirects', 'action' => 'add', $uri->id],
                    ['escape' => false]
                )?>
            </div>
        <?php }?>
    </div>
    <br/>

    <?php if(!empty($uri->meta_tags)){?>
        <div class="row">
            <div class="col-xs-12" style="font-size: 18px; margin-bottom: 10px;">
                <?=$this->Html->link(
                    '<span class="label label-default">Add</span>',
                    ['plugin' => 'IconicSeo', 'controller' => 'MetaTags', 'action' => 'add', $uri->id],
                    ['escape' => false]
                )?>
                <b>Meta Tags</b>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <?php foreach($uri->meta_tags as $tag) { ?>
                    <?php
                        echo $this->Html->link(
                            '<span class="label label-info">Edit</span>',
                            ['plugin' => 'IconicSeo', 'controller' => 'MetaTags', 'action' => 'edit', $tag->id],
                            ['escape' => false]) . " ";
                        echo $this->Html->link(
                            '<span class="label label-danger">Delete</span>',
                            ['plugin' => 'IconicSeo', 'controller' => 'MetaTags', 'action' => 'delete', $tag->id],
                            ['confirm' => 'Are you sure you wish to delete?', 'escape' => false]);
                    ?>
                    <?=h("<meta {$tag->attribute1} {$tag->attribute2}>") . "<br/><br/>";?>
                <?php }?>
            </div>
        </div>
    <?php } ?>



    <div class="row">
        <div class="col-xs-12" style="text-align: center; margin-top: 20px;">
            <?=$this->Html->link(
                'Cancel',
                ['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index'],
                ['confirm' => 'Are you sure you wish to cancel?'])
            ?> &nbsp;
            <button type="submit" class="btn btn-md btn-primary" value="save" id="save">SAVE CHANGE</button>
        </div>
    </div>
    <?=$this->Form->end();?>


</div>

src/Template/Uris/index.ctp
<?php
use Cake\Routing\Router;
echo $this->Html->css(['IconicSeo.seo_plugin.css']);
?>
<div class="block">
    <header>
        <h2>SEO Management</h2>
    </header>
    <section>
        <div class="row">
            <div class="col-xs-12">
                <div class="page-filter">
                    Sort:
                    <?= $this->Html->link(__('All'), [
                        'plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index']);
                    ?> |
                    <?= $this->Html->link(__('Created'), [
                        'plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index', 'order' => 'created']);
                    ?> |
                    <?= $this->Html->link(__('Modified'), [
                        'plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index', 'order' => 'modified']);
                    ?> &nbsp;&nbsp;&nbsp;
                    <div class="search-url-form">
                        <?=$this->Form->create(null, ['type' => 'get'], ['url' => ['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index']]);?>
                        <input type="submit" value="Search:"/>
                        <input type="text" name="kw" id="kw" />
                        <?=isset($kw) ? 'Search result: <b>' . h($kw) . '</b>' : ''?>
                        <?= $this->Form->end(); ?>
                    </div>
                </div>

                <div class="page-list">
                    <?= '<ul><li><a href="#">' . $this->Paginator->counter() . '</a></li>' . $this->Paginator->first('<<') .
                    $this->Paginator->prev('<') . $this->Paginator->numbers(['modulus' => 4]) .
                    $this->Paginator->next('>') . $this->Paginator->last('>>') . '</ul>';?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="page-filter">
                    <a href="<?=$this->Url->build(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'convert'])?>" target="_blank" class="link">
                        <span class="label label-default">CONVERT</span>
                    </a>
                    Categories:
                    <a href="<?=$this->Url->build(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index', 'filter' => 'jobs_dir'])?>">
                        <?=__('Job List')?>
                    </a> |
                    <a href="<?=$this->Url->build(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index', 'filter' => 'static_pages'])?>">
                        <?=__('Static Pages')?>
                    </a> |
                    <a href="<?=$this->Url->build(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'index', 'filter' => 'other'])?>">
                        <?=__('Others')?>
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <?php foreach($all_uris as $uri) { ?>
                    <table class="table table-bordered table-condensed url-info">
                        <thead>
                        <tr class="success">
                            <th width="66%">
                                <?=$this->Html->link(
                                    '<div class="label label-default">Edit</div>',
                                    ['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'edit', $uri->id],
                                    ['escape' => false]
                                )?>
                                <a name="uri_<?=$uri->id?>" href="http://<?=SITE_CANDIDATE_URL.$uri->uri?>" target="_blank"><?=$uri->uri?></a>
                            </th>
                            <th width="4%">
                                <?php
                                echo $this->Html->link(
                                    'Delete',
                                    Router::url(['plugin' => 'IconicSeo', 'controller' => 'Uris', 'action' => 'deleteUri', 'id' => $uri->id, 'page' => $this->Paginator->current()]),
                                    ['confirm' => 'Are you sure you wish DELETE this link?', 'class' => 'label label-danger']);
                                ?>
                            </th>
                            <th width="12%" title="created datetime"><?= !empty($uri->created) ? $uri->created->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                            <th width="12%" title="modified datetime"><?= !empty($uri->modified) ? $uri->modified->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if(!empty($uri->redirect->redirect)){ ?>
                            <tr>
                                <td>
                                    <div class="label label-warning title-lv-1">Redirect</div>
                                    <?=$uri->redirect->redirect?>
                                    <div class="label label-default"><?=$uri->redirect->type?></div>
                                </td>
                                <td><?=$uri->redirect->is_active == 1 ? '<span class="label label-danger">Active</span>' : '<span class="label label-info">Disabled</span>'?></td>
                                <td><?= !empty($uri->redirect->created) ? $uri->redirect->created->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                                <td><?= !empty($uri->redirect->modified) ? $uri->redirect->modified->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                            </tr>
                        <?php }?>
                        <?php if(!empty($uri->title->title)){ ?>
                            <tr>
                                <td colspan="2">
                                    <div class="label label-info title-lv-1">Title</div>
                                    <?= $uri->title->title?></td>
                                <td><?= !empty($uri->title->created) ? $uri->title->created->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                                <td><?= !empty($uri->title->modified) ? $uri->title->modified->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                            </tr>
                        <?php }?>

                        <?php if(!empty($uri->canonical->canonical)){ ?>
                            <tr>
                                <td colspan="2">
                                    <div class="label label-info title-lv-1">Canonical</div>
                                    <?=$uri->canonical->canonical?></td>
                                <td><?= !empty($uri->canonical->created) ? $uri->canonical->created->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                                <td><?= !empty($uri->canonical->modified) ? $uri->canonical->modified->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                            </tr>
                        <?php }?>
                        <?php if(!empty($uri->top_message->ja_top_message)){ ?>
                            <tr>
                                <td colspan="2">
                                    <div class="label label-info title-lv-1">
                                        Top Message(JA)
                                    </div>
                                    <div style="display: inline-block; padding-left: 20px;">
                                        <?=$uri->top_message->ja_top_message?>
                                    </div>
                                    <br>
                                    <br>
                                    <div class="label label-info title-lv-1">
                                        Top Message(EN)
                                    </div>
                                    <div style="display: inline-block; padding-left: 20px;">
                                        <?=$uri->top_message->en_top_message?>
                                    </div>
                                    <br>
                                    <br>
                                    <div class="label label-info title-lv-1">
                                        Top Message(VI)
                                    </div>
                                    <div style="display: inline-block; padding-left: 20px;">
                                        <?=$uri->top_message->vi_top_message?>
                                    </div>


                                </td>

                                <td><?= !empty($uri->top_message->created) ? $uri->top_message->created->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                                <td><?= !empty($uri->top_message->modified) ? $uri->top_message->modified->i18nFormat('HH:mm MM.dd.YYYY') : ''?></th>
                            </tr>
                        <?php }?>
                        <?php if(!empty($uri->meta_tags)){ ?>
                            <tr>
                                <td colspan="4">
                                    <div class="label label-info title-lv-1">Meta Tags</div>
                                    <br/>
                                    <div class="title-lv-2">
                                        <?php foreach($uri->meta_tags as $tag) {
                                            echo h("<meta {$tag->attribute1} {$tag->attribute2}>") . "<br/>";
                                        }?>
                                    </div>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                <?php }?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="page-list">
                    <?= '<ul><li><a href="#">' . $this->Paginator->counter() . '</a></li>' . $this->Paginator->first('<<') .
                    $this->Paginator->prev('<') . $this->Paginator->numbers(['modulus' => 4]) .
                    $this->Paginator->next('>') . $this->Paginator->last('>>') . '</ul>';?>
                </div>
            </div>
        </div>
    </section>
</div>